# Generated by Django 4.2.7 on 2025-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_miles',
            field=models.FloatField(default=0.0),
        ),
    ]
