# Generated by Django 4.2.7 on 2025-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_trip_total_hours_trip_total_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='distance_from_previous',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stop',
            name='duration_from_previous',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
